waypoints:
  - x: -1.62
    y: 1.70
    yaw: 1.5708
  - x: -1.74
    y: 0.48
    yaw: 3.11
  - x: -0.98
    y: 0.44
    yaw: 1.60
  - x: -0.90
    y: 0.56
    yaw: -1.56
  - x: -0.19
    y: 0.45
    yaw: -1.46
  - x: -0.12
    y: -1.71
    yaw: 0.08
  - x: 1.06
    y: -1.61
    yaw: 1.64
  - x: 1.02
    y: -0.93
    yaw: -0.01
  - x: 1.06
    y: 1.74
    yaw: -0.02
  - x: 1.76
    y: 1.65
    yaw: 3.14