robot_radius: 0.1
inflation_radius: 0.15
obstacle_range: 1.0
raytrace_range: 6.0
robot_base_frame: base_footprint
observation_sources: base_lidar
base_lidar: {
    data_type: LaserScan,
    topic: /scan, 
    marking: true, 
    clearing: true
    }