local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.3