# 全局配置
move_base:
  ros__parameters:
    # 坐标系与变换配置（与模型保持一致）
    base_frame_id: base_footprint
    global_frame_id: map
    odom_frame_id: odom
    transform_tolerance: 0.3  # 坐标变换容忍时间

    # 规划频率
    controller_frequency: 10.0  # 局部规划器更新频率（Hz）
    planner_frequency: 1.0      # 全局规划器更新频率（Hz，静态环境可设低）
    planner_patience: 5.0       # 全局规划超时时间（s）
    controller_patience: 15.0   # 局部规划超时时间（s）

    # 恢复行为（遇到障碍时）
    recovery_behavior_enabled: true
    clearing_rotation_allowed: true

    # 全局规划器配置（Navfn）
    base_global_planner: navfn/NavfnROS
    navfn_ros:
      allow_unknown: true        # 允许规划到未知区域
      default_tolerance: 0.2     # 目标点容忍误差（m）
      visualize_potential: false # 是否可视化势场

    # 局部规划器配置（DWA）
    base_local_planner: dwa_local_planner/DWAPlannerROS
    dwa_local_planner:
      # 底盘物理参数（与xacro模型匹配）
      max_vel_x: 0.5             # 最大线速度（m/s）
      min_vel_x: 0.0             # 最小线速度（m/s）
      max_vel_y: 0.0             # 差速车无法横向移动，设为0
      min_vel_y: 0.0
      max_vel_theta: 1.0         # 最大角速度（rad/s）
      min_vel_theta: -1.0        # 最小角速度（rad/s）
      min_in_place_vel_theta: 0.4 # 原地旋转最小角速度（rad/s）
      escape_vel: -0.1           # 后退逃离速度（m/s）

      # 加速度限制（根据实际动力调整）
      acc_lim_x: 0.5             # x方向加速度限制（m/s²）
      acc_lim_y: 0.0             # y方向加速度限制（差速车为0）
      acc_lim_theta: 1.0         # 角加速度限制（rad/s²）

      # 规划时间与窗口
      sim_time: 1.5              # 模拟预测时间（s）
      vx_samples: 20             # x方向速度采样数
      vy_samples: 1              # y方向采样数（差速车为1）
      vtheta_samples: 40         # 角速度采样数

      # 代价地图权重（影响局部路径选择）
      path_distance_bias: 32.0   # 路径跟踪权重（越大越贴路径）
      goal_distance_bias: 24.0   # 目标点权重（越大越优先靠近目标）
      occdist_scale: 0.01        # 障碍物距离权重（越大越避障）
      forward_point_distance: 0.3 # 预瞄点距离（m）
      stop_time_buffer: 0.2      # 到达目标后停留时间（s）
      scaling_speed: 0.25        # 速度缩放阈值（m/s）
      max_scaling_factor: 0.2    # 最大速度缩放系数

      # 障碍物处理
      oscillation_reset_dist: 0.05 # 重置震荡判断的移动距离（m）
      obstacle_range: 2.5          # 障碍物检测范围（m）
      raytrace_range: 3.0          # 射线追踪范围（m）

# 全局代价地图配置
global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_footprint
    transform_tolerance: 0.3
    update_frequency: 1.0        # 全局地图更新频率（Hz）
    publish_frequency: 0.5       # 全局地图发布频率（Hz）
    static_map: true             # 使用静态地图
    rolling_window: false        # 不使用滚动窗口（全局地图固定）
    origin_x: -100.0               # 地图原点x坐标（m）
    origin_y: -100.0               # 地图原点y坐标（m）
    resolution: 0.05             # 地图分辨率（m/格）

    # 膨胀参数（根据底盘半径0.1m设置，避免碰撞）
    inflation_layer:
      inflation_radius: 0.2      # 膨胀半径（底盘半径+安全距离）
      cost_scaling_factor: 10.0  # 代价缩放因子（越大膨胀代价衰减越快）

    # 障碍物图层
    obstacle_layer:
      enabled: true
      obstacle_range: 2.5
      raytrace_range: 3.0
      observation_sources: laser_scan_sensor
      laser_scan_sensor:
        data_type: LaserScan
        topic: scan              # 激光雷达话题（根据实际修改）
        marking: true            # 标记障碍物
        clearing: true           # 清除已消失障碍物

# 局部代价地图配置
local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_footprint
    transform_tolerance: 0.3
    update_frequency: 5.0        # 局部地图更新频率（Hz，高于全局）
    publish_frequency: 2.0       # 局部地图发布频率（Hz）
    static_map: false            # 不使用静态地图（局部动态更新）
    rolling_window: true         # 使用滚动窗口（随机器人移动）
    width: 5.0                   # 局部地图宽度（m）
    height: 5.0                  # 局部地图高度（m）
    resolution: 0.05             # 地图分辨率（m/格）

    # 膨胀参数（与全局地图一致）
    inflation_layer:
      inflation_radius: 0.2
      cost_scaling_factor: 10.0

    # 障碍物图层（同全局，但更新更频繁）
    obstacle_layer:
      enabled: true
      obstacle_range: 2.5
      raytrace_range: 3.0
      observation_sources: laser_scan_sensor
      laser_scan_sensor:
        data_type: LaserScan
        topic: scan
        marking: true
        clearing: true